export const VALID_TIMEFRAMES = ["all", "daily", "weekly", "monthly"] as const;
export type ValidTimeframe = (typeof VALID_TIMEFRAMES)[number];

export const VALID_LANGUAGES = [
  "en",
  "es",
  "fr",
  "de",
  "it",
  "pt",
  "ru",
  "zh",
  "ja",
  "ko",
  "ar",
  "hi",
  "nl",
  "pl",
  "sv",
  "tr",
  "vi",
  "th",
  "id",
  "ms",
  "mr",
  "bn",
  "ta",
  "te",
] as const;
export type ValidLanguage = (typeof VALID_LANGUAGES)[number];

export const VALID_PROGRAMMING_LANGUAGES = [
  "javascript",
  "typescript",
  "python",
  "java",
  "cpp",
  "csharp",
  "go",
  "rust",
  "swift",
  "ruby",
  "php",
  "html",
  "css",
  "scss",
  "sass",
  "less",
  "jsx",
  "tsx",
  "kotlin",
  "dart",
  "scala",
  "groovy",
  "objectivec",
  "c",
  "zig",
  "vhdl",
  "r",
  "julia",
  "matlab",
  "bash",
  "powershell",
  "perl",
  "lua",
  "elixir",
  "haskell",
  "clojure",
  "fsharp",
  "ocaml",
  "erlang",
  "scheme",
  "racket",
  "lisp",
  "sql",
  "json",
  "yaml",
  "toml",
  "xml",
  "markdown",
  "fortran",
  "nim",
  "crystal",
  "d",
  "solidity",
  "pascal",
] as const;
export type ValidProgrammingLanguage = (typeof VALID_PROGRAMMING_LANGUAGES)[number];

export const VALID_STRESS_DIFFICULTIES = [
  "beginner",
  "intermediate",
  "expert",
  "nightmare",
  "impossible",
] as const;
export type ValidStressDifficulty = (typeof VALID_STRESS_DIFFICULTIES)[number];

export const VALID_RATING_TIERS = [
  "bronze",
  "silver",
  "gold",
  "platinum",
  "diamond",
  "master",
  "grandmaster",
] as const;
export type ValidRatingTier = (typeof VALID_RATING_TIERS)[number];

export const VALID_BOOK_TOPICS = [
  "fiction",
  "classics",
  "adventure",
  "mystery",
  "science-fiction",
  "philosophy",
  "history",
] as const;
export type ValidBookTopic = (typeof VALID_BOOK_TOPICS)[number];
